version: '3.8'

services:
  app:
    image: node:18
    container_name: my_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "${APP_PORT}:${APP_PORT}"  # Redirection du port de l'hôte vers le conteneur
    environment:
      - PORT=${APP_PORT}  # Transmet la variable à l'application Express
      - MONGO_URI=${MONGO_URI}
    command: npm start
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_local
    restart: always
    ports:
      - "27017:27017"
